##############################################################################
# ______     ______     ______     ______     _____     ______     ______    #
# /\  == \   /\  ___\   /\  ___\   /\  __ \   /\  __-.  /\  __ \   /\  ___\  #
# \ \  __<   \ \  __\   \ \ \____  \ \  __ \  \ \ \/\ \ \ \ \/\ \  \ \___  \ #
# \ \_\ \_\  \ \_____\  \ \_____\  \ \_\ \_\  \ \____-  \ \_____\  \/\_____\ #
# \/_/ /_/   \/_____/   \/_____/   \/_/\/_/   \/____/   \/_____/   \/_____/  #
##############################################################################

permission: 'recados.ver'

recados:
- '     &4&lFACTIONS MAGMA &7(Temporada #1983891872891)'
- ''
- '   &eSim, este é o servidor que você já jogou 500 vezes'
- '   &esó que com o sistema de dungeon, the end e cofre'
- '   &ea mesma coisa que tu não cansa de ver nos ultimos servidores.'
- '   &eNão temos mais ideia do que fazer, só queremos dinheiro'
- ''